site_name: MidiTok
theme:
  name: readthedocs
plugins:
  - exclude:
      glob:
        - Design documentation/*
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_options:
              ignore_init_summary: false
              #merge_init_into_class: true
  - autorefs:
      link_titles: false
